language: bash
dist: xenial

env:
  - TARANTOOL_VERSION=1.10
  - TARANTOOL_VERSION=2x

# tarantool
before_install:
  - curl http://download.tarantool.org/tarantool/$TARANTOOL_VERSION/gpgkey | sudo apt-key add -
  - echo "deb http://download.tarantool.org/tarantool/$TARANTOOL_VERSION/ubuntu/ xenial main" |
    sudo tee /etc/apt/sources.list.d/tarantool.list
  - sudo apt-get -y update
  - sudo apt-get install -y tarantool tarantool-dev

# homebrew
install:
  - sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  - echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile

script:
  - brew install https://github.com/artur-barsegyan/tarantool-lsp/raw/impl-cli-tools/tarantoollsp.rb --HEAD
  - tarantool-lsp docs init
  - tarantool-lsp docs update


