language: bash
dist: xenial

env:
  - TARANTOOL_VERSION=1.10
  - TARANTOOL_VERSION=2x

# tarantool
before_install:
  - curl http://download.tarantool.org/tarantool/$TARANTOOL_VERSION/gpgkey | sudo apt-key add -
  - echo "deb http://download.tarantool.org/tarantool/$TARANTOOL_VERSION/ubuntu/ xenial main" |
    sudo tee /etc/apt/sources.list.d/tarantool.list
  - sudo apt-get -y update
  - sudo apt-get install -y tarantool tarantool-dev

# homebrew, see: https://github.com/Homebrew/linuxbrew/issues/47
install:
  - git clone https://github.com/Homebrew/linuxbrew.git ~/.linuxbrew
  - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig:/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib64/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH
  - export LINUXBREWHOME=$HOME/.linuxbrew
  - export PATH=$LINUXBREWHOME/bin:$PATH
  - export MANPATH=$LINUXBREWHOME/man:$MANPATH
  - export PKG_CONFIG_PATH=$LINUXBREWHOME/lib64/pkgconfig:$LINUXBREWHOME/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$LINUXBREWHOME/lib64:$LINUXBREWHOME/lib:$LD_LIBRARY_PATH
  - brew update || true

script:
  - brew install https://github.com/artur-barsegyan/tarantool-lsp/raw/impl-cli-tools/tarantoollsp.rb --HEAD
  - tarantool-lsp docs init
  - tarantool-lsp docs update


